#!/usr/bin/env python
# -*- encoding: utf-8 -*-

"""
fls.py

Terminal command that expands on the functionality of the `ls` command by grouping files by 
their tags.

Attributes:
    args (list): a list of the arguments passed in by the user where each argument is a string
        in the collection
"""

import os
import sys
import glob
import subprocess

def main(args):
    """ Parse user input and execute command """

    # get only the first argument, can be file/dir
    # path or help tag
    user_input = args[1]

    # tag
    if user_input[0] == "-":
        print("Help")

    # file or directory
    elif os.path.isdir(user_input) or os.path(user_input):
        # readability
        path = user_input

        # call mdls on file path
        file_metadata = subprocess.check_call(["mdls", path])

    else:
        print("Not a valid argument.")

if __name__ == "__main__":
    main(sys.argv)    

